export const STORAGE_KEYS = {
  apiKey: "elevenlabs_key",
  voiceFr: "elevenlabs_voice_fr",
  voiceEn: "elevenlabs_voice_en",
  introSeen: "emerge_first_guide_seen_v2",
  notes: "emerge_reflection_notes_v2",
};

export const I18N = {
  fr: {
    navStart: "Emerge",
    navGuide: "Guide",
    navFaq: "FAQ",
    navNotes: "Mes notes",
    firstWelcome: "Bienvenue sur Emerge.",
    firstGuidePrompt: "Avant ta première session, lis le guide.",
    firstGuideCta: "Guide",
    title: "EMERGE",
    welcome: "Ton espace pour\nrelâcher",
    press: "Choisis une durée pour commencer.",
    listening: "Je t'écoute.",
    speaking: "Je te le renvoie.",
    stopped: "Session fermée. Tu peux recommencer quand tu veux.",
    noMic: "Autorise l'accès au micro pour pratiquer.",
    noChrome: "Utilise Chrome pour tester la reconnaissance vocale.",
    you: "Toi",
    voice: "Voix",
    stopHint: "Appuie à nouveau pour arrêter",
    homeCta: "ENTER",
    homeTagline: "Ton espace pour relâcher",
    homeSecondary: "Everything you feel is welcome",
    introTitle: "Comment fonctionne la pratique",
    // Texte de la page Guide en français : un paragraphe par ligne.
    introReadText: [
      "Emerge est une pratique vocale pour laisser sortir ce que tu ressens, sans le transformer en analyse.",
      "Tu parles à voix haute. L'app te renvoie tes mots. Tu les répètes, puis tu continues.",
      "Ce cadre très simple a un but : rester au contact du corps. Les mots n'ont pas besoin d'être parfaits ; ils doivent seulement être vrais maintenant.",
      "Pour commencer, amène ton attention dans ton corps. Respire. Ferme les yeux si ça t'aide.",
      "Dis une phrase courte : « je suis triste », « je sens une tension », « je ne sais pas », ou autre chose qui sonne juste.",
      "Quand la phrase revient, répète-la. Garde-la le temps qu'il faut. Si une autre phrase apparaît d'elle-même et semble plus juste, suis-la.",
      "Laisse le mouvement aider : relâche les épaules, marche, balance-toi, secoue les bras, respire plus profondément.",
      "Ne cherche pas à bien faire, ni à forcer un changement. Laisse ce qui bouge bouger.",
      "La première partie dure le temps que tu choisis. À la fin, le closing démarre automatiquement pour garder la continuité de la pratique.",
      "Si tu sens que tu veux continuer, tu pourras interrompre le closing et reprendre la pratique.",
      "Si l'intensité monte trop pendant la pratique, appuie sur Ground pour revenir doucement au présent.",
    ],
    practiceTitle: "Pratique",
    practiceLead: "Ressens. Exprime. Répète.",
    practiceBody: "Une phrase suffit. Reste avec elle, laisse ton corps participer, puis change seulement si une autre phrase vient naturellement.",
    practiceDurationKicker: "Durée",
    durationPrompt: "Commençons.",
    durationRecommendedValue: "15 min",
    durationRecommendedLabel: "Recommended",
    durationTestValue: "10 sec",
    durationTestLabel: "Test",
    durationCustomLabel: "Custom",
    durationError: "Choisis une durée entre 12 et 60 minutes.",
    practiceStart: "Commencer",
    sessionInProgress: "En cours",
    practiceLiveCopy: "Tout ce que tu ressens est bienvenu",
    closingStatus: "Closing.",
    closingCopy: "intégration",
    closingAudioText: "La session se termine. Garde les yeux fermés si c'est confortable. Sens tes pieds. Sens le poids de ton corps. Laisse ce qui a bougé se déposer. Tu n'as rien à résoudre maintenant. Inspire doucement. Expire doucement. Reviens à la pièce autour de toi, à ton rythme.",
    postClosingStatus: "Closing terminé.",
    sessionContinuePracticeCta: "continuer la pratique plutôt",
    sessionClosePracticeCta: "terminer la pratique",
    sessionWriteCta: "Reflect",
    sessionEndCta: "End",
    sessionClosedStatus: "Session fermée.",
    groundCta: "Ground",
    groundStatus: "Grounding.",
    groundText: "Stop. Regarde autour de toi et nomme trois choses que tu vois. Sens tes pieds au sol. Pose une main sur ton coeur, une main sur ton ventre. Inspire lentement par le nez. Expire par la bouche. Trois fois. Tu es ici, maintenant.",
    groundTitle: "Respire, et sens ton corps",
    groundReturnCta: "Retour à la pratique",
    endMessage: "Thank you ♥",
    reflectTitle: "Qu'est-ce qui a émergé ?",
    reflectPlaceholder: "Écris ici...",
    reflectSendLabel: "Enregistrer la note",
    reflectSaved: "Enregistré",
    reflectEmptyStatus: "Écris quelques mots avant d'enregistrer.",
    notesTitle: "Mes notes",
    notesAddTodayCta: "Ajouter des notes aujourd'hui",
    notesReadCta: "Lire mes notes",
    notesEmpty: "Aucune note pour le moment.",
    faqIntro: "Continue à explorer comment utiliser Emerge",
    contactTitle: "Ta question n'est pas ici ?",
    contactCta: "Écrire à Alexia",
    howTitle: "Le geste",
    howText: "Parle à voix haute. L'app te renvoie tes mots.<br><br>Répète-les, respire, laisse ton corps répondre. Change seulement quand une phrase plus juste vient d'elle-même.",
    // Questions/réponses de la FAQ en français.
    faqItems: [
      {
        q: "Qu'est-ce que Emerge ?",
        a: "Une pratique vocale d'expression émotionnelle. Tu dis ce qui est vrai dans l'instant, tu l'entends revenir, puis tu le répètes pour laisser de la place à ce qui bouge.",
      },
      {
        q: "Comment se déroule une session ?",
        a: "Amène ton attention dans ton corps, dis une phrase courte, écoute-la revenir, puis répète. Continue jusqu'à sentir un changement naturel.",
      },
      {
        q: "Pourquoi garder la même phrase ?",
        a: "Parce que rester donne du temps au corps. Cela évite de partir trop vite dans l'analyse, la performance ou le contrôle.",
      },
      {
        q: "Quand changer de phrase ?",
        a: "Seulement si une autre phrase vient d'elle-même et semble plus honnête dans le corps. Tu n'as pas besoin de varier pour bien faire.",
      },
      {
        q: "Et si je ne sais pas quoi dire ?",
        a: "Commence par la vérité la plus simple : « je sens une tension », « je me sens lourde », « je ne sais pas ». C'est suffisant.",
      },
      {
        q: "Est-ce que je dois bouger ?",
        a: "Tu n'es pas obligée, mais ça aide souvent. Marche, balance-toi, relâche les épaules, secoue les bras, ou ferme les yeux.",
      },
      {
        q: "Que faire si ça devient trop intense ?",
        a: "Appuie sur Ground et suis les étapes d'ancrage. Si la détresse est forte, persistante, ou si tu te sens en danger, contacte un professionnel ou les services d'urgence.",
      },
      {
        q: "Est-ce une thérapie ?",
        a: "Non. Emerge est une pratique guidée d'expression émotionnelle. Ce n'est ni un soin médical, ni une psychothérapie, ni un dispositif de crise.",
      },
    ],
  },
  en: {
    navStart: "Emerge",
    navGuide: "Guide",
    navFaq: "FAQ",
    navNotes: "My Notes",
    firstWelcome: "Welcome to Emerge.",
    firstGuidePrompt: "Before your first session, it is important that you read the guide.",
    firstGuideCta: "Guide",
    title: "EMERGE",
    welcome: "This is your space\nto release",
    press: "Choose a duration to begin.",
    listening: "Listening.",
    speaking: "Giving it back.",
    stopped: "Session closed. Start again whenever you want.",
    noMic: "Allow microphone access to practice.",
    noChrome: "Use Chrome to test speech recognition.",
    you: "You",
    voice: "Voice",
    stopHint: "Press again to stop",
    homeCta: "ENTER",
    homeTagline: "This is your space to release",
    homeSecondary: "Everything you feel is welcome",
    introTitle: "How the practice works",
    // English Guide page text: one paragraph per line.
    introReadText: [
      "Express your emotions, without explaining, without analysing, so that they can move easily and profoundly.",
      "Repetition is used to avoid thinking, and fully focus on the feeling.",
      "How to do it:",
      "1. Bring your attention to your body.",
      "2. Say a simple sentence that expresses your feeling, with no explanation.",
      "3. Listen to the app repeating, then repeat again. Example, you say: “I’m sad” app: “You’re sad” you: “I’m sad” app: “You’re sad” etc",
      "4. Continue to repeat. Move your body. Let go.",
      "5. Allow changes in feelings to change the sentence, and do the same repetition with this new sentence. Do not try to change, let change happen, if it does happen. Be open to staying in the same feeling for a while.",
      "6. Repeat or change as many times as you want. Don’t try to do it perfectly. What matters is that what you say helps you even if it doesn’t match exactly how you feel.",
      "During the whole practice, invite your body to move. Do not retain anything, express yourself fully, say what you feel like saying, focus, repeat, be courageous, face things, let go, enjoy, be yourself!",
      "If you suddenly need to stop, press the Grounding button.",
      "The practice invites you to feel all emotions, including difficult ones. If you stay with them long enough, they will probably move. But if you really need to get away, the grounding button will help you.",
    ],
    practiceTitle: "Practice",
    practiceLead: "Feel. Express. Repeat.",
    practiceBody: "One sentence is enough. Stay with it, let your body take part, and change only when another sentence comes naturally.",
    practiceDurationKicker: "Duration",
    durationPrompt: "Let's begin.",
    durationRecommendedValue: "15 min",
    durationRecommendedLabel: "Recommended",
    durationTestValue: "10 sec",
    durationTestLabel: "Test",
    durationCustomLabel: "Custom",
    durationError: "Choose a duration between 12 and 60 minutes.",
    practiceStart: "Start",
    sessionInProgress: "In progress",
    practiceLiveCopy: "Everything you feel is welcome",
    closingStatus: "Closing.",
    closingCopy: "integration",
    closingAudioText: "The session is closing. Keep your eyes closed if that feels comfortable. Feel your feet. Feel the weight of your body. Let what moved settle. There is nothing to solve right now. Breathe in softly. Breathe out softly. Come back to the room around you, at your own pace.",
    postClosingStatus: "Closing complete.",
    sessionContinuePracticeCta: "Continue the practice instead",
    sessionClosePracticeCta: "close the session",
    sessionWriteCta: "Reflect",
    sessionEndCta: "End",
    sessionClosedStatus: "Session closed.",
    groundCta: "Ground",
    groundStatus: "Grounding.",
    groundText: "Stop. Look around and name three things you can see. Feel your feet on the ground. Place one hand on your heart and one hand on your belly. Breathe in slowly through your nose. Exhale through your mouth. Three times. You are here, now.",
    groundTitle: "breath and feel your body",
    groundReturnCta: "Return to practice",
    endMessage: "Thank you ♥",
    reflectTitle: "What emerged?",
    reflectPlaceholder: "Write here...",
    reflectSendLabel: "Save note",
    reflectSaved: "Saved",
    reflectEmptyStatus: "Write a few words before saving.",
    notesTitle: "My Notes",
    notesAddTodayCta: "Add notes for today",
    notesReadCta: "Read my notes",
    notesEmpty: "No notes yet.",
    faqIntro: "Keep exploring how to use Emerge",
    contactTitle: "Your question is not in there ?",
    contactCta: "Write to Alexia",
    howTitle: "The gesture",
    howText: "Speak out loud. The app gives your words back to you.<br><br>Repeat them, breathe, and let your body respond. Change only when a truer sentence arrives by itself.",
    // English FAQ questions/answers.
    faqItems: [
      {
        q: "What is Emerge?",
        a: "A voice-based emotional expression practice. You say what is true in the moment, hear it returned, and repeat it so the feeling has space to move.",
      },
      {
        q: "How does a session work?",
        a: "Bring attention into your body, say one short sentence, listen to it coming back, then repeat. Continue until something naturally shifts.",
      },
      {
        q: "Why stay with the same sentence?",
        a: "Because staying gives the body time. It keeps the mind from rushing into explanation, performance, or control.",
      },
      {
        q: "When should I change sentences?",
        a: "Only when another sentence arrives by itself and feels more honest in the body. You do not need to vary for the sake of it.",
      },
      {
        q: "What if I don't know what to say?",
        a: "Start with the simplest truth: “I feel tension,” “I feel heavy,” or “I don't know.” That is enough.",
      },
      {
        q: "Should I move?",
        a: "You do not have to, but it often helps. Walk, sway, shake your arms, release your shoulders, or close your eyes.",
      },
      {
        q: "What if it becomes too intense?",
        a: "Press Ground and follow the grounding steps. If distress feels strong, persistent, or unsafe, contact a trusted professional or emergency services.",
      },
      {
        q: "Is this therapy?",
        a: "No. Emerge is a guided practice for emotional expression. It is not medical care, psychotherapy, or a crisis service.",
      },
    ],
  },
};

export const VOICE_PRESETS = {
  fr: [
    { value: "EXAVITQu4vr4xnSDxMaL", label: "Bella" },
    { value: "XB0fDUnXU5powFXDhCwa", label: "Charlotte" },
    { value: "MF3mGyEYCl7XYWbV9V6O", label: "Elli" },
    { value: "pNInz6obpgDQGcFmaJgB", label: "Adam" },
    { value: "ErXwobaYiN019PkySvjV", label: "Antoni" },
    { value: "onwK4e9ZLuTAKqWW03F9", label: "Daniel" },
  ],
  en: [
    { value: "ErXwobaYiN019PkySvjV", label: "Antoni" },
    { value: "pNInz6obpgDQGcFmaJgB", label: "Adam" },
    { value: "onwK4e9ZLuTAKqWW03F9", label: "Daniel" },
    { value: "TxGEqnHWrfWFTfGW9XjX", label: "Josh" },
    { value: "VR6AewLTigWG4xSOukaG", label: "Arnold" },
    { value: "EXAVITQu4vr4xnSDxMaL", label: "Bella" },
    { value: "XB0fDUnXU5powFXDhCwa", label: "Charlotte" },
    { value: "MF3mGyEYCl7XYWbV9V6O", label: "Elli" },
  ],
};
