export const STORAGE_KEYS = {
  apiKey: "elevenlabs_key",
  voiceFr: "elevenlabs_voice_fr",
  voiceEn: "elevenlabs_voice_en",
  introSeen: "emerge_first_guide_seen_v2",
  notes: "emerge_reflection_notes_v2",
};

export const I18N = {
  fr: {
    navStart: "Emerge",
    navGuide: "Guide",
    navFaq: "FAQ",
    navNotes: "Mes notes",
    firstWelcome: "Bienvenue sur Emerge.",
    firstGuidePrompt: "Avant ta première session, lis le guide.",
    firstGuideCta: "Guide",
    title: "EMERGE",
    welcome: "Ton espace pour\nrelâcher",
    press: "Choisis une durée pour commencer.",
    listening: "Je t'écoute.",
    speaking: "Je te le renvoie.",
    stopped: "Session fermée. Tu peux recommencer quand tu veux.",
    noMic: "Autorise l'accès au micro pour pratiquer.",
    noChrome: "Utilise Chrome pour tester la reconnaissance vocale.",
    you: "Toi",
    voice: "Voix",
    stopHint: "Appuie à nouveau pour arrêter",
    homeCta: "ENTER",
    homeTagline: "Ton espace pour relâcher",
    homeSecondary: "Everything you feel is welcome",
    introTitle: "Comment fonctionne la pratique",
    // Texte de la page Guide en français : un paragraphe par ligne.
    introReadText: [
      "Emerge est une pratique vocale pour laisser sortir ce que tu ressens, sans le transformer en analyse.",
      "Tu parles à voix haute. L'app te renvoie tes mots. Tu les répètes, puis tu continues.",
      "Ce cadre très simple a un but : rester au contact du corps. Les mots n'ont pas besoin d'être parfaits ; ils doivent seulement être vrais maintenant.",
      "Pour commencer, amène ton attention dans ton corps. Respire. Ferme les yeux si ça t'aide.",
      "Dis une phrase courte : « je suis triste », « je sens une tension », « je ne sais pas », ou autre chose qui sonne juste.",
      "Quand la phrase revient, répète-la. Garde-la le temps qu'il faut. Si une autre phrase apparaît d'elle-même et semble plus juste, suis-la.",
      "Laisse le mouvement aider : relâche les épaules, marche, balance-toi, secoue les bras, respire plus profondément.",
      "Ne cherche pas à bien faire, ni à forcer un changement. Laisse ce qui bouge bouger.",
      "La première partie dure le temps que tu choisis. À la fin, le closing démarre automatiquement pour garder la continuité de la pratique.",
      "Si tu sens que tu veux continuer, tu pourras interrompre le closing et reprendre la pratique.",
      "Si l'intensité monte trop pendant la pratique, appuie sur Safety stop pour revenir doucement au présent.",
    ],
    practiceTitle: "Pratique",
    practiceLead: "Ressens. Exprime. Répète.",
    practiceBody: "Une phrase suffit. Reste avec elle, laisse ton corps participer, puis change seulement si une autre phrase vient naturellement.",
    practiceDurationKicker: "Durée",
    durationPrompt: "Commençons.",
    durationRecommendedValue: "15 min",
    durationRecommendedLabel: "Recommended",
    durationTestValue: "10 sec",
    durationTestLabel: "Test",
    durationCustomLabel: "Custom",
    durationError: "Choisis une durée entre 12 et 60 minutes.",
    practiceStart: "Commencer",
    sessionInProgress: "En cours",
    practiceLiveCopy: "Tout ce que tu ressens est bienvenu",
    closingStatus: "Closing.",
    closingCopy: "intégration",
    closingAudioText: "La session se termine. Garde les yeux fermés si c'est confortable. Sens tes pieds. Sens le poids de ton corps. Laisse ce qui a bougé se déposer. Tu n'as rien à résoudre maintenant. Inspire doucement. Expire doucement. Reviens à la pièce autour de toi, à ton rythme.",
    postClosingStatus: "Closing terminé.",
    sessionContinuePracticeCta: "continuer la pratique plutôt",
    sessionClosePracticeCta: "terminer la pratique",
    sessionWriteCta: "Reflect",
    sessionEndCta: "End",
    sessionClosedStatus: "Session fermée.",
    remindPracticeCta: "Revoir les instructions 🤓",
    completePracticeCta: "J'ai terminé, fermer la session 😌",
    safetyStopCta: "Trop intense, j'ai besoin d'aide 🛟",
    introReturnCta: "Retour à la pratique",
    groundCta: "Ground",
    groundStatus: "Grounding.",
    groundGuidanceLabel: "Retour au calme...",
    groundEndGuidanceCta: "Terminer la guidance",
    groundText: "Stop. Regarde autour de toi et nomme trois choses que tu vois. Sens tes pieds au sol. Pose une main sur ton coeur, une main sur ton ventre. Inspire lentement par le nez. Expire par la bouche. Trois fois. Tu es ici, maintenant.",
    groundTitle: "",
    groundBetterCta: "Je me sens mieux",
    groundMoreCta: "J'ai encore besoin d'aide",
    supportTitle: "Voici quelques choses qui peuvent aider :",
    supportTips: [
      "🌬 Respiration lente (5 s inspire, 5 s expire)",
      "💧 Rince-toi le visage à l'eau froide",
      "🚶 Fais une courte marche dehors",
      "✍️ Écris ce que tu ressens",
      "👤 Contacte une personne de confiance",
      "🛏 Repose-toi dans un endroit confortable",
    ],
    supportContinueCta: "Continuer",
    breathingIn: "Inspire",
    breathingOut: "Expire",
    breathingEndCta: "Terminer la respiration",
    breathingStatus: "Respiration guidée.",
    endMessage: "Thank you ♥",
    reflectTitle: "Qu'est-ce qui a émergé ?",
    reflectPlaceholder: "Écris ici...",
    reflectSendLabel: "Enregistrer la note",
    reflectSaved: "Enregistré",
    reflectEmptyStatus: "Écris quelques mots avant d'enregistrer.",
    notesTitle: "Mes notes",
    notesAddTodayCta: "Ajouter des notes aujourd'hui",
    notesReadCta: "Lire mes notes",
    notesEmpty: "Aucune note pour le moment.",
    faqIntro: "Continue à explorer comment utiliser Emerge",
    contactTitle: "Ta question n'est pas ici ?",
    contactCta: "Écrire à Alexia",
    howTitle: "Le geste",
    howText: "Parle à voix haute. L'app te renvoie tes mots.<br><br>Répète-les, respire, laisse ton corps répondre. Change seulement quand une phrase plus juste vient d'elle-même.",
    // Questions/réponses de la FAQ en français.
    faqItems: [
      {
        q: "Qu'est-ce que Emerge ?",
        a: "Une pratique vocale d'expression émotionnelle. Tu dis ce qui est vrai dans l'instant, tu l'entends revenir, puis tu le répètes pour laisser de la place à ce qui bouge.",
      },
      {
        q: "Comment se déroule une session ?",
        a: "Amène ton attention dans ton corps, dis une phrase courte, écoute-la revenir, puis répète. Continue jusqu'à sentir un changement naturel.",
      },
      {
        q: "Pourquoi garder la même phrase ?",
        a: "Parce que rester donne du temps au corps. Cela évite de partir trop vite dans l'analyse, la performance ou le contrôle.",
      },
      {
        q: "Quand changer de phrase ?",
        a: "Seulement si une autre phrase vient d'elle-même et semble plus honnête dans le corps. Tu n'as pas besoin de varier pour bien faire.",
      },
      {
        q: "Et si je ne sais pas quoi dire ?",
        a: "Commence par la vérité la plus simple : « je sens une tension », « je me sens lourde », « je ne sais pas ». C'est suffisant.",
      },
      {
        q: "Est-ce que je dois bouger ?",
        a: "Tu n'es pas obligée, mais ça aide souvent. Marche, balance-toi, relâche les épaules, secoue les bras, ou ferme les yeux.",
      },
      {
        q: "Que faire si ça devient trop intense ?",
        a: "Appuie sur Safety stop et suis les étapes d'ancrage. Si la détresse est forte, persistante, ou si tu te sens en danger, contacte un professionnel ou les services d'urgence.",
      },
      {
        q: "Est-ce une thérapie ?",
        a: "Non. Emerge est une pratique guidée d'expression émotionnelle. Ce n'est ni un soin médical, ni une psychothérapie, ni un dispositif de crise.",
      },
    ],
  },
  en: {
    navStart: "Emerge",
    navGuide: "Guide",
    navFaq: "FAQ",
    navNotes: "My Notes",
    firstWelcome: "Welcome to Emerge.",
    firstGuidePrompt: "Before your first session, take a moment to read the guide.",
    firstGuideCta: "Guide",
    title: "EMERGE",
    welcome: "This is your space\nto release",
    press: "Choose a duration to begin.",
    listening: "Listening.",
    speaking: "Repeating it back.",
    stopped: "Session closed. Start again whenever you want.",
    noMic: "Allow microphone access to begin the practice.",
    noChrome: "Use Chrome to test speech recognition.",
    you: "You",
    voice: "Voice",
    stopHint: "Press again to stop",
    homeCta: "ENTER",
    homeTagline: "This is your space to release",
    homeSecondary: "Everything you feel is welcome",
    introTitle: "How the practice works",
    // English Guide page text: one paragraph per line.
    introReadText: [
      "Express what you feel without explaining or analysing it, so the feeling has space to move.",
      "How to do it:",
      "1. Bring your attention to your body.",
      "2. Say a simple sentence that names what you feel, without explaining why.",
      "3. The app changes “I” to “you” where needed and repeats the sentence back. Then say it again.",
      "For example: you say, “I’m sad.” The app says, “You’re sad.” You say, “I’m sad.” The app says, “You’re sad,” and so on.",
      "4. Stay with the sentence. Let your body move in whatever way feels natural.",
      "5. If your feeling changes and another sentence arises by itself, follow it. There is no need to force a change.",
      "6. Repeat or change sentences as many times as you need. The words do not have to be perfect; they only need to help you stay with what you feel.",
      "You can keep your eyes open or closed, move or remain still, and stop at any time.",
      "If the practice becomes too intense, tap “I need support” to stop the repetition and begin a grounding guidance.",
    ],
    practiceTitle: "Practice",
    practiceLead: "Feel. Express. Repeat.",
    practiceBody: "One sentence is enough. Stay with it, let your body take part, and change only when another sentence comes naturally.",
    practiceDurationKicker: "Duration",
    durationPrompt: "Let's begin.",
    durationRecommendedValue: "15 min",
    durationRecommendedLabel: "Recommended",
    durationTestValue: "10 sec",
    durationTestLabel: "Test",
    durationCustomLabel: "Custom",
    durationError: "Choose a duration between 12 and 60 minutes.",
    practiceStart: "Start",
    sessionInProgress: "In progress",
    practiceLiveCopy: "Everything you feel is welcome",
    closingStatus: "Closing.",
    closingCopy: "integration",
    closingAudioText: "The practice is ending now. Keep your eyes closed if that feels comfortable. Let your body be supported by the position you are in. Notice your breathing without changing it. Feel your feet. Feel your hands. Notice where your body meets the floor, the chair, or the bed. Let your body integrate what it has just experienced. There is nothing to understand or solve right now. Begin to notice the sounds in the room. Invite a small movement into your fingers and toes. When you are ready, open your eyes. Take all the time you need. You can reflect on what emerged, or simply end the session.",
    postClosingStatus: "Closing complete.",
    sessionContinuePracticeCta: "Continue the session",
    sessionClosePracticeCta: "Finish the session",
    sessionWriteCta: "Reflect",
    sessionEndCta: "End",
    sessionClosedStatus: "Session closed.",
    remindPracticeCta: "Review instructions 🤓",
    completePracticeCta: "End session 😌",
    safetyStopCta: "I need support 🛟",
    introReturnCta: "Go back to the practice",
    groundCta: "Ground",
    groundStatus: "Grounding.",
    groundGuidanceLabel: "Calming down...",
    groundEndGuidanceCta: "End the guidance",
    groundText: "Pause. The practice has stopped. Find the most comfortable position you can. Feel the support beneath your body. If it feels comfortable, place a hand on your chest or anywhere that feels steady. Notice your breathing without needing to change it. Let your exhale become a little longer. Look around and notice three things you can see. Feel your feet or your hands. Invite a small movement into your fingers or toes. You are here, and you can take all the time you need. When you are ready, choose whether you feel a little better or still need support.",
    groundTitle: "",
    groundBetterCta: "I feel a little better",
    groundMoreCta: "I still need support",
    supportTitle: "Here are a few things that often help:",
    supportTips: [
      "🌬 Slow breathing (5s in, 5s out)",
      "💧 Rinse your face with cold water",
      "🚶 Take a short walk outside",
      "✍️ Write down what you're feeling",
      "👤 Reach out to someone you trust",
      "🛏 Rest somewhere that feels comfortable",
    ],
    supportContinueCta: "Continue",
    breathingIn: "Breathe in",
    breathingOut: "Breathe out",
    breathingEndCta: "End breathing",
    breathingStatus: "Breathing guidance.",
    endMessage: "Thank you ♥",
    reflectTitle: "What emerged?",
    reflectPlaceholder: "Write here...",
    reflectSendLabel: "Save note",
    reflectSaved: "Saved",
    reflectEmptyStatus: "Write a few words before saving.",
    notesPrivacy: "Your notes stay on this iPhone.",
    notesTitle: "My Notes",
    notesAddTodayCta: "Add notes for today",
    notesReadCta: "Read my notes",
    notesEmpty: "No notes yet.",
    faqIntro: "Keep exploring how to use Emerge",
    contactTitle: "Didn't find your answer?",
    contactCta: "Write to Alexia",
    contactBoundary: "This contact is not monitored as an emergency service.",
    recognitionError: "I couldn't hear that clearly. Try saying the sentence again.",
    networkError: "The connection was interrupted. Check your connection and try again.",
    retryCta: "Try again",
    microphoneDisclosure: "Emerge uses the microphone to hear and repeat your words during the practice.",
    safetyShort: "Emerge is a wellness practice for emotional expression. It is not medical care, psychotherapy, or a crisis service. You are always in control: pause or stop at any time. If you feel unsafe or are in immediate danger, stop using the app and contact local emergency services or a trusted person nearby.",
    safetyFull: "Emerge invites you to focus on feelings and body sensations, which can sometimes feel intense. Use it only when you are in a physically safe place and are not driving or doing anything that requires your full attention. You can keep your eyes open, remain still, change position, pause, or stop at any time. If you feel overwhelmed, use the support button or end the session. Emerge does not diagnose or treat any medical or mental health condition, and it is not a substitute for care from a qualified professional. If distress is intense or persistent, contact a qualified healthcare professional. If you feel unsafe or are in immediate danger, contact local emergency services or a trusted person nearby. The first beta is intended for adults aged 18 or over.",
    howTitle: "The gesture",
    howText: "Speak out loud. The app gives your words back to you.<br><br>Repeat them, breathe, and let your body respond. Change only when a truer sentence arrives by itself.",
    // English FAQ questions/answers.
    faqItems: [
      {
        q: "What is Emerge?",
        a: "A voice-based emotional expression practice. You say what is true in the moment, hear it returned, and repeat it so the feeling has space to move.",
      },
      {
        q: "How does a session work?",
        a: "Bring attention into your body, say one short sentence, listen to it coming back, then repeat. Continue until something naturally shifts.",
      },
      {
        q: "Why stay with the same sentence?",
        a: "Repeating means you no longer have to decide what to say. It can help you leave analysis, stay with one feeling, and experience it more fully.",
      },
      {
        q: "When should I change sentences?",
        a: "When another sentence arises by itself and feels more truthful in your body. There is no need to change for the sake of it.",
      },
      {
        q: "What if my sentence no longer matches how I feel, but no new sentence has appeared?",
        a: "It is fine to keep saying it. Something may already have shifted, even if the sentence no longer fits exactly. The aim is not to describe your experience perfectly.",
      },
      {
        q: "What if I don't know how I feel?",
        a: "Describe a body sensation instead: “I feel warmth in my hands,” “I feel tingling in my belly,” or simply, “I feel something in my chest.”",
      },
      {
        q: "What if I feel several things at once?",
        a: "Start with whatever feels most present. The choice does not have to be perfect, and you can return to the other feelings later.",
      },
      {
        q: "Should I move?",
        a: "You can invite the feeling to move through your body in whatever way feels natural. You can also stay in a resting position. There is no need to force movement.",
      },
      {
        q: "What are the most common mistakes?",
        a: "Explaining the feeling instead of naming it; trying to force the feeling to change; or holding your body still when it wants to move. Notice these tendencies without judging yourself, then return to what you feel now.",
      },
      {
        q: "What if it becomes too intense?",
        a: "Tap “I need support” to stop the repetition and begin the grounding guidance. You can end the session at any time. If you feel unsafe or are in immediate danger, contact local emergency services or a trusted person nearby.",
      },
      {
        q: "Why do this practice?",
        a: "You may find it useful when you want to make space for what you feel instead of distracting yourself or getting caught in analysis.",
      },
      {
        q: "Is this therapy?",
        a: "No. Emerge is a guided wellness practice for emotional expression. It is not medical care, psychotherapy, or a crisis service.",
      },
    ],
  },
};

export const VOICE_PRESETS = {
  fr: [
    { value: "EXAVITQu4vr4xnSDxMaL", label: "Bella" },
    { value: "XB0fDUnXU5powFXDhCwa", label: "Charlotte" },
    { value: "MF3mGyEYCl7XYWbV9V6O", label: "Elli" },
    { value: "pNInz6obpgDQGcFmaJgB", label: "Adam" },
    { value: "ErXwobaYiN019PkySvjV", label: "Antoni" },
    { value: "onwK4e9ZLuTAKqWW03F9", label: "Daniel" },
  ],
  en: [
    { value: "ErXwobaYiN019PkySvjV", label: "Antoni" },
    { value: "pNInz6obpgDQGcFmaJgB", label: "Adam" },
    { value: "onwK4e9ZLuTAKqWW03F9", label: "Daniel" },
    { value: "TxGEqnHWrfWFTfGW9XjX", label: "Josh" },
    { value: "VR6AewLTigWG4xSOukaG", label: "Arnold" },
    { value: "EXAVITQu4vr4xnSDxMaL", label: "Bella" },
    { value: "XB0fDUnXU5powFXDhCwa", label: "Charlotte" },
    { value: "MF3mGyEYCl7XYWbV9V6O", label: "Elli" },
  ],
};
