import { I18N } from "./app-config.js";

function lines(...values) {
  return values.filter(Boolean).join("\n");
}

function guide(lang) {
  return I18N[lang].introReadText.join("\n\n");
}

function faq(lang) {
  return I18N[lang].faqItems
    .map((item, index) => `${index + 1}. ${item.q}\n${item.a}`)
    .join("\n\n");
}

function supportList(lang) {
  return lines(
    I18N[lang].supportTitle,
    "",
    ...I18N[lang].supportTips,
  );
}

export const WRITING_CATEGORIES = [
  { id: "foundation", label: "Fondations" },
  { id: "audio", label: "Guidances audio" },
  { id: "experience", label: "Parcours dans l’app" },
  { id: "safety", label: "Confiance et sécurité" },
  { id: "launch", label: "Bêta et lancement" },
];

export const WRITING_PRIORITIES = {
  now: {
    label: "À écrire maintenant",
    shortLabel: "Maintenant",
    description: "Le cœur de la voix et de la compréhension d’Emerge.",
  },
  beta: {
    label: "Avant la bêta",
    shortLabel: "Bêta",
    description: "Les textes nécessaires pour une expérience complète et sûre.",
  },
  later: {
    label: "Pour le lancement",
    shortLabel: "Plus tard",
    description: "Les textes publics à préparer après validation du produit.",
  },
};

export const WRITING_STATUSES = [
  { id: "write", label: "À écrire" },
  { id: "review", label: "À revoir" },
  { id: "draft", label: "Brouillon" },
  { id: "final", label: "Validé" },
];

export const WRITING_ITEMS = [
  {
    id: "brand-home",
    category: "foundation",
    priority: "now",
    kind: "Écran",
    title: "Promesse et homepage",
    objective: "Faire sentir en quelques mots qu’Emerge est un espace profond, direct et accueillant, sans expliquer toute la méthode.",
    formatHint: "4 micro-textes · très courts",
    prompts: [
      "Quelle sensation doit rester après trois secondes sur l’écran ?",
      "Que promet Emerge sans promettre un résultat médical ?",
      "Le ton est-il aussi élégant à voix haute qu’à l’écrit ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        `Nom : ${I18N.fr.title}`,
        `Phrase centrale : ${I18N.fr.homeTagline}`,
        `Bouton : ${I18N.fr.homeCta}`,
        `Phrase secondaire : ${I18N.fr.homeSecondary}`,
      ),
      en: lines(
        `Name: ${I18N.en.title}`,
        `Main line: ${I18N.en.homeTagline}`,
        `Button: ${I18N.en.homeCta}`,
        `Secondary line: ${I18N.en.homeSecondary}`,
      ),
    },
  },
  {
    id: "first-launch-written",
    category: "foundation",
    priority: "now",
    kind: "Écran",
    title: "Premier lancement · accueil écrit",
    objective: "Accueillir sans intimider et faire comprendre que le guide est important avant la première session.",
    formatHint: "2 phrases + 1 bouton",
    prompts: [
      "La personne se sent-elle bienvenue plutôt qu’obligée ?",
      "Comprend-elle pourquoi lire le guide sans avoir peur de mal faire ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(I18N.fr.firstWelcome, I18N.fr.firstGuidePrompt, `Bouton : ${I18N.fr.firstGuideCta}`),
      en: lines(I18N.en.firstWelcome, I18N.en.firstGuidePrompt, `Button: ${I18N.en.firstGuideCta}`),
    },
  },
  {
    id: "written-guide",
    category: "foundation",
    priority: "now",
    kind: "Guide",
    title: "Guide écrit complet",
    objective: "Permettre à une personne de pratiquer correctement dès sa première session, avec assez de précision sans transformer le guide en cours théorique.",
    formatHint: "Lecture cible · 2 à 4 minutes",
    prompts: [
      "Le rôle de la répétition est-il parfaitement compris ?",
      "Le mouvement du corps et le changement spontané de phrase sont-ils clairs ?",
      "La personne sait-elle quoi faire si elle se sent dépassée ?",
    ],
    initialStatus: "review",
    initial: {
      fr: guide("fr"),
      en: guide("en"),
    },
  },
  {
    id: "faq",
    category: "foundation",
    priority: "now",
    kind: "FAQ",
    title: "Questions fréquentes",
    objective: "Répondre aux hésitations qui empêchent de pratiquer, sans répéter le guide mot pour mot.",
    formatHint: "6 à 10 questions · réponses courtes",
    prompts: [
      "Chaque réponse résout-elle une vraie hésitation ?",
      "Quelles questions apparaîtront après une première session réelle ?",
      "Les limites d’Emerge sont-elles formulées calmement et clairement ?",
    ],
    initialStatus: "review",
    initial: {
      fr: faq("fr"),
      en: faq("en"),
    },
  },
  {
    id: "audio-first-welcome",
    category: "audio",
    priority: "now",
    kind: "Audio",
    title: "Audio · accueil première fois",
    objective: "Créer une entrée courte, chaleureuse et rassurante avant l’explication complète.",
    formatHint: "Durée cible · 15 à 30 secondes",
    prompts: [
      "La personne sent-elle immédiatement qu’elle peut ralentir ?",
      "L’audio prépare-t-il l’attention sans déjà tout expliquer ?",
      "Les premières secondes donnent-elles envie de rester ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "audio-first-guide",
    category: "audio",
    priority: "now",
    kind: "Audio",
    title: "Audio · guide première session",
    objective: "Expliquer toute la pratique à l’oral avec un rythme naturel, des respirations et une progression facile à suivre.",
    formatHint: "Durée cible · 2 à 4 minutes",
    prompts: [
      "Le texte sonne-t-il comme une présence plutôt que comme une notice ?",
      "Où faut-il laisser de vrais silences ?",
      "La personne sait-elle exactement quoi faire à la fin de l’audio ?",
    ],
    initialStatus: "write",
    initial: {
      fr: guide("fr"),
      en: guide("en"),
    },
  },
  {
    id: "audio-returning-opening",
    category: "audio",
    priority: "now",
    kind: "Audio",
    title: "Audio · ouverture habituelle",
    objective: "Faire passer rapidement une personne habituée de sa journée à son corps, puis à sa première phrase.",
    formatHint: "Durée cible · 10 à 25 secondes",
    prompts: [
      "Peut-on entrer dans la pratique sans aucune explication superflue ?",
      "La dernière phrase ouvre-t-elle naturellement l’écoute ?",
      "Le rythme laisse-t-il le temps de fermer les yeux ou de bouger ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "audio-closing",
    category: "audio",
    priority: "now",
    kind: "Audio",
    title: "Audio · closing et intégration",
    objective: "Ramener progressivement l’attention vers le corps et la pièce, sans casser ce qui vient de se passer ni imposer une interprétation.",
    formatHint: "Durée cible · 60 à 120 secondes",
    prompts: [
      "La transition commence-t-elle sans effet de rupture ?",
      "Les silences laissent-ils le temps au corps de suivre ?",
      "La fin ouvre-t-elle agréablement sur la suite de la journée ?",
    ],
    initialStatus: "review",
    initial: {
      fr: I18N.fr.closingAudioText,
      en: I18N.en.closingAudioText,
    },
  },
  {
    id: "audio-grounding",
    category: "audio",
    priority: "now",
    kind: "Audio",
    title: "Audio · aide et grounding",
    objective: "Soutenir une personne possiblement dépassée avec une voix très simple, lente, concrète et non alarmante.",
    formatHint: "Durée cible · 60 à 180 secondes",
    prompts: [
      "Chaque instruction est-elle faisable immédiatement ?",
      "Le texte évite-t-il toute pression à aller mieux ?",
      "La fin prépare-t-elle clairement les deux choix de soutien ?",
    ],
    initialStatus: "review",
    initial: {
      fr: I18N.fr.groundText,
      en: I18N.en.groundText,
    },
  },
  {
    id: "navigation-common",
    category: "experience",
    priority: "beta",
    kind: "Interface",
    title: "Navigation et mots communs",
    objective: "Créer un vocabulaire stable et évident dans toute l’app.",
    formatHint: "Micro-copy · 1 à 4 mots",
    prompts: [
      "Le même geste porte-t-il toujours le même verbe ?",
      "Les mots français et anglais ont-ils la même chaleur ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        `Navigation : ${I18N.fr.navStart} · ${I18N.fr.navGuide} · ${I18N.fr.navFaq} · ${I18N.fr.navNotes}`,
        `Accueil : ${I18N.fr.homeCta}`,
        `Fin : ${I18N.fr.sessionEndCta}`,
      ),
      en: lines(
        `Navigation: ${I18N.en.navStart} · ${I18N.en.navGuide} · ${I18N.en.navFaq} · ${I18N.en.navNotes}`,
        `Home: ${I18N.en.homeCta}`,
        `End: ${I18N.en.sessionEndCta}`,
      ),
    },
  },
  {
    id: "duration-setup",
    category: "experience",
    priority: "beta",
    kind: "Écran",
    title: "Choix de la durée",
    objective: "Faire commencer la session avec le moins de réflexion possible tout en rendant les choix parfaitement clairs.",
    formatHint: "1 phrase + libellés",
    prompts: [
      "Le choix recommandé paraît-il naturel sans être autoritaire ?",
      "L’option personnalisée est-elle compréhensible instantanément ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        I18N.fr.durationPrompt,
        `${I18N.fr.durationRecommendedValue} · ${I18N.fr.durationRecommendedLabel}`,
        `${I18N.fr.durationCustomLabel} · 12–60 min`,
        `Erreur : ${I18N.fr.durationError}`,
      ),
      en: lines(
        I18N.en.durationPrompt,
        `${I18N.en.durationRecommendedValue} · ${I18N.en.durationRecommendedLabel}`,
        `${I18N.en.durationCustomLabel} · 12–60 min`,
        `Error: ${I18N.en.durationError}`,
      ),
    },
  },
  {
    id: "live-practice",
    category: "experience",
    priority: "beta",
    kind: "Écran",
    title: "Pratique en cours",
    objective: "Rassurer sans retenir le regard sur l’écran et rendre les trois sorties possibles émotionnellement distinctes.",
    formatHint: "1 phrase + 3 boutons",
    prompts: [
      "La phrase centrale laisse-t-elle toute émotion exister ?",
      "Les boutons sont-ils clairs sans rompre l’état de pratique ?",
      "Le soutien paraît-il accessible sans devenir alarmant ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        I18N.fr.practiceLiveCopy,
        I18N.fr.remindPracticeCta,
        I18N.fr.completePracticeCta,
        I18N.fr.safetyStopCta,
      ),
      en: lines(
        I18N.en.practiceLiveCopy,
        I18N.en.remindPracticeCta,
        I18N.en.completePracticeCta,
        I18N.en.safetyStopCta,
      ),
    },
  },
  {
    id: "closing-interface",
    category: "experience",
    priority: "beta",
    kind: "Écrans",
    title: "Closing, intégration et fin",
    objective: "Nommer les étapes de fin avec douceur et permettre de continuer, réfléchir ou terminer sans ambiguïté.",
    formatHint: "Titres + 5 actions",
    prompts: [
      "Le mot intégration correspond-il réellement à l’expérience ?",
      "Continuer la pratique reste-t-il possible sans dominer le closing ?",
      "Reflect et End sont-ils cohérents avec le ton de l’app ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        I18N.fr.closingCopy,
        I18N.fr.sessionContinuePracticeCta,
        I18N.fr.sessionClosePracticeCta,
        I18N.fr.sessionWriteCta,
        I18N.fr.sessionEndCta,
        I18N.fr.endMessage,
      ),
      en: lines(
        I18N.en.closingCopy,
        I18N.en.sessionContinuePracticeCta,
        I18N.en.sessionClosePracticeCta,
        I18N.en.sessionWriteCta,
        I18N.en.sessionEndCta,
        I18N.en.endMessage,
      ),
    },
  },
  {
    id: "grounding-interface",
    category: "experience",
    priority: "beta",
    kind: "Écran",
    title: "Aide · guidance terminée",
    objective: "Après le grounding, proposer deux choix très simples à une personne qui peut encore être vulnérable.",
    formatHint: "1 statut + 3 actions",
    prompts: [
      "Les deux choix sont-ils compréhensibles avec très peu d’énergie mentale ?",
      "Aucun mot ne culpabilise-t-il la personne qui a encore besoin d’aide ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        I18N.fr.groundGuidanceLabel,
        I18N.fr.groundEndGuidanceCta,
        I18N.fr.groundBetterCta,
        I18N.fr.groundMoreCta,
      ),
      en: lines(
        I18N.en.groundGuidanceLabel,
        I18N.en.groundEndGuidanceCta,
        I18N.en.groundBetterCta,
        I18N.en.groundMoreCta,
      ),
    },
  },
  {
    id: "support-list",
    category: "safety",
    priority: "beta",
    kind: "Écran",
    title: "Liste de soutien supplémentaire",
    objective: "Donner quelques actions concrètes, douces et réalistes sans présenter une liste écrasante ni remplacer une aide professionnelle.",
    formatHint: "1 introduction + 5 à 7 actions",
    prompts: [
      "Chaque proposition est-elle accessible immédiatement ?",
      "L’ordre commence-t-il par les options les plus simples ?",
      "La liste convient-elle à quelqu’un qui se sent dépassé ?",
    ],
    initialStatus: "review",
    initial: {
      fr: supportList("fr"),
      en: supportList("en"),
    },
  },
  {
    id: "breathing-interface",
    category: "experience",
    priority: "beta",
    kind: "Écran",
    title: "Respiration guidée",
    objective: "Rendre le rythme 5 secondes / 5 secondes évident sans demander de lire pendant l’exercice.",
    formatHint: "3 micro-textes",
    prompts: [
      "Les mots peuvent-ils être compris d’un seul regard ?",
      "Le bouton de sortie est-il calme mais trouvable ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(I18N.fr.breathingIn, I18N.fr.breathingOut, I18N.fr.breathingEndCta),
      en: lines(I18N.en.breathingIn, I18N.en.breathingOut, I18N.en.breathingEndCta),
    },
  },
  {
    id: "reflection-notes",
    category: "experience",
    priority: "beta",
    kind: "Écrans",
    title: "Reflection et My Notes",
    objective: "Inviter à écrire sans transformer la fin de session en devoir ni en analyse forcée.",
    formatHint: "1 question + actions et états",
    prompts: [
      "La question ouvre-t-elle sans diriger la réponse ?",
      "La personne comprend-elle que l’écriture est facultative ?",
      "Les actions de sauvegarde sont-elles rassurantes ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        I18N.fr.reflectTitle,
        I18N.fr.reflectPlaceholder,
        I18N.fr.reflectSendLabel,
        I18N.fr.reflectSaved,
        I18N.fr.notesAddTodayCta,
        I18N.fr.notesReadCta,
        I18N.fr.notesEmpty,
      ),
      en: lines(
        I18N.en.reflectTitle,
        I18N.en.reflectPlaceholder,
        I18N.en.reflectSendLabel,
        I18N.en.reflectSaved,
        I18N.en.notesAddTodayCta,
        I18N.en.notesReadCta,
        I18N.en.notesEmpty,
      ),
    },
  },
  {
    id: "permissions-errors",
    category: "experience",
    priority: "beta",
    kind: "Système",
    title: "Permissions, états et erreurs",
    objective: "Expliquer un problème technique sans jargon et toujours donner une prochaine action claire.",
    formatHint: "Messages de 1 phrase",
    prompts: [
      "Chaque erreur dit-elle ce qui s’est passé et quoi faire ensuite ?",
      "Le ton reste-t-il humain sans minimiser le problème ?",
      "Que voit-on si le réseau disparaît au milieu d’une session ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(
        I18N.fr.listening,
        I18N.fr.speaking,
        I18N.fr.noMic,
        I18N.fr.durationError,
        I18N.fr.reflectEmptyStatus,
      ),
      en: lines(
        I18N.en.listening,
        I18N.en.speaking,
        I18N.en.noMic,
        I18N.en.durationError,
        I18N.en.reflectEmptyStatus,
      ),
    },
  },
  {
    id: "safety-boundaries",
    category: "safety",
    priority: "beta",
    kind: "Document",
    title: "Cadre, limites et sécurité",
    objective: "Dire clairement ce qu’Emerge est et n’est pas, et orienter vers une aide adaptée sans rendre l’expérience anxiogène.",
    formatHint: "Version courte + version complète",
    prompts: [
      "Le texte évite-t-il toute promesse thérapeutique ou médicale ?",
      "La conduite à tenir en cas de danger immédiat est-elle explicite ?",
      "Où ce texte doit-il apparaître pour être réellement vu ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "contact-support",
    category: "safety",
    priority: "beta",
    kind: "Écran",
    title: "Contact et aide utilisateur",
    objective: "Permettre de poser une question ou signaler un problème avec une formulation simple et accueillante.",
    formatHint: "1 question + 1 action",
    prompts: [
      "La personne sait-elle quel type de réponse elle peut attendre ?",
      "Le contact ne ressemble-t-il pas à une assistance d’urgence ?",
    ],
    initialStatus: "review",
    initial: {
      fr: lines(I18N.fr.contactTitle, I18N.fr.contactCta),
      en: lines(I18N.en.contactTitle, I18N.en.contactCta),
    },
  },
  {
    id: "privacy-policy",
    category: "launch",
    priority: "later",
    kind: "Document",
    title: "Politique de confidentialité",
    objective: "Expliquer précisément le traitement de la voix, des transcriptions, des notes et des données techniques.",
    formatHint: "Document public · validation juridique",
    prompts: [
      "Quelles données quittent l’iPhone et pendant combien de temps ?",
      "Comment supprimer toutes ses données ?",
      "Quels prestataires tiers interviennent réellement ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "app-store",
    category: "launch",
    priority: "later",
    kind: "Store",
    title: "Page App Store",
    objective: "Présenter clairement l’expérience et sa différence sans surpromesse ni vocabulaire thérapeutique.",
    formatHint: "Nom · sous-titre · description · mots-clés",
    prompts: [
      "Quelle transformation concrète peut-on promettre honnêtement ?",
      "Qu’est-ce qui distingue Emerge en une phrase ?",
      "Les captures et le texte racontent-ils la même expérience ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "website",
    category: "launch",
    priority: "later",
    kind: "Site",
    title: "Site de présentation",
    objective: "Donner envie de découvrir Emerge, expliquer la pratique et accueillir les inscriptions à la bêta.",
    formatHint: "Homepage + méthode + sécurité + contact",
    prompts: [
      "Que doit comprendre une personne qui ne voit qu’un seul écran ?",
      "Comment expliquer la répétition sans jargon ?",
      "Quelle preuve ou quel retour pourra rassurer sans exagérer ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "beta-invite",
    category: "launch",
    priority: "later",
    kind: "Bêta",
    title: "Invitation et accueil des bêta-testeurs",
    objective: "Expliquer ce que les testeurs vont essayer, comment se préparer et comment partager leurs retours.",
    formatHint: "Invitation + message TestFlight + rappel",
    prompts: [
      "Le testeur sait-il ce qui est encore expérimental ?",
      "Quelles conditions rendent le test vocal utile ?",
      "Comment demander un retour honnête sans orienter ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "ux-questionnaire",
    category: "launch",
    priority: "later",
    kind: "Recherche",
    title: "Questionnaire UX",
    objective: "Mesurer compréhension, fluidité, sécurité et valeur émotionnelle sans suggérer les réponses.",
    formatHint: "Questionnaire court + entretien",
    prompts: [
      "Quelles décisions produit chaque question doit-elle éclairer ?",
      "Que faut-il demander immédiatement après la session ?",
      "Qu’est-ce qui mérite plutôt une conversation ouverte ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
  {
    id: "instagram",
    category: "launch",
    priority: "later",
    kind: "Réseaux",
    title: "Instagram · bio et premiers contenus",
    objective: "Installer l’univers d’Emerge avec une voix reconnaissable avant de chercher à publier beaucoup.",
    formatHint: "Bio + 6 publications fondatrices",
    prompts: [
      "Quels sujets donnent immédiatement la personnalité d’Emerge ?",
      "Quelle place laisser à la pédagogie, à l’esthétique et au vécu ?",
      "Comment éviter le ton wellness générique ?",
    ],
    initialStatus: "write",
    initial: { fr: "", en: "" },
  },
];
